version: '3.1'

services:

  db:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234       # change me
      POSTGRES_DB: random_numbers
    networks:
      - app-tier
    ports:
    - "5432:5432"

networks:
  app-tier:
    driver: bridge